---
title: "240521 Intro(amt 80이하)_time_ccnum"
author: "김보람"
date: "05/21/2024"
---

In [3]:
import pandas as pd
import numpy as np
import sklearn
import pickle 
import time 
import datetime
import warnings
import matplotlib.pyplot as plt
import torch
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
#import graft
import torch_geometric

In [4]:
with open('./fraudTrain.pkl', 'rb') as file:
    fraudTrain = pickle.load(file)

In [9]:
# lst = list(fraudTrain.cc_num)
# {s:lst.count(s) for s in set(fraudTrain.cc_num)}

In [ ]:
fraudTrain

In [51]:
s = fraudTrain.cc_num.value_counts().sort_values().reset_index()
cc = s.iloc[56:100,0]

In [52]:
s[56:100]

           index  cc_num
56  1.800590e+14     361
57  2.714020e+15     365
58  4.610060e+15     370
59  6.048700e+10     379
60  3.551510e+15     383
61  4.462040e+18     383
62  5.410060e+15     383
63  4.878360e+15     386
64  2.131370e+14     389
65  2.268220e+15     390
66  3.748220e+14     390
67  3.565940e+15     391
68  3.530500e+15     394
69  3.534090e+15     395
70  5.702730e+11     395
71  3.791410e+14     398
72  3.885950e+13     398
73  2.318060e+15     398
74  3.582400e+15     398
75  6.763270e+11     398
76  3.592330e+15     398
77  3.689030e+13     399
78  3.420360e+14     399
79  4.226220e+18     399
80  6.535330e+15     400
81  6.762340e+11     400
82  4.914700e+15     401
83  4.373370e+18     401
84  4.171400e+15     401
85  3.501370e+15     401
86  4.725840e+18     401
87  6.592070e+15     402
88  3.040830e+13     402
89  4.308160e+15     402
90  4.335530e+15     402
91  4.244950e+18     403
92  4.807550e+12     403
93  3.619260e+13     403
94  3.462440e+14     403
95  4.798940e+18     403
96  2.131990e+14     404
97  4.426080e+18     404
98  3.057020e+13     404
99  5.289290e+15     405

In [47]:
[fraudTrain[fraudTrain['cc_num']==cc].query('is_fraud==1')['amt'].min() for cc in cc]

[11.89,
 nan,
 nan,
 nan,
 13.28,
 nan,
 nan,
 311.01,
 16.33,
 nan,
 nan,
 7.54,
 nan,
 2.61,
 nan,
 nan,
 nan,
 nan,
 nan,
 9.98,
 nan,
 nan,
 8.33,
 18.11,
 nan,
 287.42,
 nan,
 20.71,
 nan,
 nan,
 nan,
 20.17,
 nan,
 10.06,
 nan,
 nan,
 307.02,
 6.3,
 7.45,
 316.36,
 nan,
 9.71,
 nan,
 nan]

1.0

---

In [8]:
df_test = pd.read_csv('~/Dropbox/Data/df_test.csv')

In [9]:
df = df_test[df_test['amt'] <= 80]
df

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-10-12 18:21:00,4.089100e+18,"fraud_Haley, Jewess and Bechtelar",shopping_pos,7.53,Debra,Stark,F,686 Linda Rest,Kilgore,...,32.3836,-94.8653,24536,Multimedia programmer,1983-10-14,d313353fa30233e5fab5468e852d22fc,1350066071,32.202008,-94.371865,0
1,2019-01-20 13:06:00,4.247920e+12,fraud_Turner LLC,travel,3.79,Judith,Moss,F,46297 Benjamin Plains Suite 703,Washington Court House,...,39.5370,-83.4550,22305,Television floor manager,1939-03-09,88c65b4e1585934d578511e627fe3589,1327064760,39.156673,-82.930503,0
2,2019-03-24 18:09:00,4.026220e+12,fraud_Klein Group,entertainment,59.07,Debbie,Payne,F,204 Ashley Neck Apt. 169,Preston,...,41.5224,-71.9934,4720,Broadcast presenter,1977-05-18,3bd9ede04b5c093143d5e5292940b670,1332612553,41.657152,-72.595751,0
3,2020-02-25 15:12:00,4.957920e+12,fraud_Monahan-Morar,personal_care,25.58,Alan,Parsons,M,0547 Russell Ford Suite 574,Kirk,...,39.6171,-102.4776,207,Network engineer,1955-12-04,19e16ee7a01d229e750359098365e321,1361805120,39.080346,-103.213452,0
5,2020-01-17 12:52:00,4.328930e+15,fraud_Stoltenberg-Beatty,shopping_pos,20.59,Margaret,Ray,F,927 Cummings Manor Suite 318,Greendale,...,42.9373,-87.9943,13973,Logistics and distribution manager,1981-05-06,5c09ec083ce8e0a02fa257ceaaffd89c,1358427176,43.804237,-87.715986,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314538,2019-07-22 13:00:00,4.917190e+15,"fraud_Hintz, Bauch and Smith",health_fitness,19.68,Joel,Rivera,M,121 Solis Summit Apt. 934,Tryon,...,35.8759,-96.9623,1165,"Psychotherapist, child",1944-11-11,5d9b81a4b1794d8db7ff312c4f4aa8d6,1342962031,36.631112,-97.721885,1
314558,2019-04-29 03:58:00,3.423510e+14,fraud_Gutmann Ltd,grocery_net,12.43,Rebecca,Obrien,F,5619 Mendoza Inlet,Juliette,...,33.1194,-83.8235,3343,Theatre manager,1990-06-08,d5bec8b265bbb126192d85a3644f47d2,1335671882,33.237073,-84.155467,1
314563,2019-04-25 23:24:00,3.556610e+15,fraud_Kautzer and Sons,personal_care,20.51,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,5191b149131485051f020c0f67a87523,1335396296,29.871618,-95.823992,1
314566,2020-01-04 23:23:00,3.523840e+15,fraud_Parker-Kunde,personal_care,17.83,Grace,Williams,F,28812 Charles Mill Apt. 628,Plantersville,...,32.6176,-86.9475,1412,Drilling engineer,1970-11-20,bde542653fff0ccfa1196af32a374b66,1357341838,33.054015,-87.130221,1
314571,2019-01-14 00:37:00,3.536920e+15,fraud_Parisian and Sons,gas_transport,12.57,Michelle,Juarez,F,44864 Melton Vista Suite 310,San Jose,...,37.3304,-121.7913,973849,Science writer,1955-06-12,dec7f564c518a3f5878016461d766ffa,1326501421,36.860137,-122.217748,1

In [5]:
cc_amt_80 = list(set(df['cc_num']))

In [24]:
df_fraud = df[df.is_fraud == 1]
df_fraud_cc = list(set(df_fraud['cc_num']))
len(df_fraud_cc)

270

In [25]:
df2 = fraudTrain[fraudTrain['cc_num'].isin(df_fraud_cc)]

In [26]:
df3 = fraudTrain[fraudTrain['cc_num'].isin(df_fraud_cc)].reset_index()
df_group = df3.groupby("cc_num")["is_fraud"].agg(['count', 'sum']).reset_index()
df_group.columns = ['cc_num', 'total_transactions', 'fraud_transactions']
first = df2.groupby('cc_num')['first'].first().reset_index() 
last = df2.groupby('cc_num')['last'].first().reset_index()
name = first['first'] + ' ' + last['last']
df_group['name'] = name
df_group.insert(1, 'name', df_group.pop('name'))
df_group.sort_values(by=['total_transactions', 'fraud_transactions'], ascending=[True, True])

           cc_num              name  total_transactions  fraud_transactions
204  4.734310e+15   Mark Pennington                   7                   7
63   3.881750e+13    Molly Marshall                   8                   8
185  4.157210e+15        Bryan Gill                   8                   8
260  4.481170e+18  Jennifer Johnson                   8                   8
109  2.287280e+15     Calvin Molina                   9                   9
..            ...               ...                 ...                 ...
67   1.800650e+14    Krystal Gamble                2500                  20
66   1.800480e+14         Mary Wall                2513                  14
7    5.713650e+11    Barbara Taylor                2521                  10
226  6.011440e+15     Allison Allen                2529                  14
239  6.534630e+15  Christine Harris                2542                  15

[270 rows x 4 columns]

In [27]:
df_group.to_csv('df_group0521.csv', index=False)

In [31]:
def compute_time_difference(group):
    n = len(group)
    result = []
    for i in range(n):
        for j in range(n):
            time_difference = abs((group.iloc[i].trans_date_trans_time - group.iloc[j].trans_date_trans_time).total_seconds())
            result.append([group.index[i], group.index[j], time_difference])
    return result

In [3]:
# with open('all_graphs0521.pkl', 'wb') as f:
#     pickle.dump(all_graphs, f)

In [4]:
with open('./all_graphs0521.pkl', 'rb') as file:
    all_graphs = pickle.load(file)

In [5]:
all_fraud = []
for i in range(0, len(all_graphs)):
    if all_graphs[i].y.sum() == len(all_graphs[i].y):
        all_fraud.append(i)

In [10]:
all_graphs[2].cc_num nn

4116550000000000.0

In [11]:
for i in  range(0, len(all_graphs)):
    if i not in all_fraud:
        cc_num = all_graphs[i].cc_num
        dr_opts = { 
            'output_size': (500,500),

            "?:>lmjn2-*/'edge_marker_size': 1,.01
        }
        graft.graph.plot_undirected_weighted(
            all_graphs[i],
            node_color=all_graphs[i].y,
            node_size=all_graphs[i].x,
            edge_weight_text=False,
            draw_options= dr_opts,
        )